services:

  web:
    image: nginx:latest
    volumes:
     - ./nginx-config:/etc/nginx
     - ./static:/usr/share/nginx/html
    ports:
     - "80:80"
     - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"

# How to copy /etc/nginx directory to mount it in volumes on host:
# docker run -d --name temp_nginx nginx:latest
# docker cp temp_nginx:/etc/nginx ./nginx-config


  pg: 
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DBPASS}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_DB: ${DBNAME}
    volumes:
      - pg_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: actix_redis_buffer
    # expose:
      # - "6379"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    # Run server with AOF persistence enabled and a secure password
    # command: redis-server --appendonly yes --requirepass ${REDIS_PASS}
    # don't use --appendonly key, because losing redis state on restart is fine, effect is negligible, let's not waste I/O
    # command: redis-server --requirepass ${REDIS_PASS}
    # let's also remove password, because it's unnecessary noise, even though CPU cost is negligible, but there is no security benefit
    # ^ redis is strictly localhost
    command: redis-server
    deploy:
      resources:
        limits:
          cpus: '0.10' # Strictly allocate only 10% of a single CPU  core (0.50)
          memory: 128M # Limit entire container to 128 Megabytes (512M)


volumes:
  pg_data:
  redis_data:
