//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ContentStatus;
use super::sea_orm_active_enums::ContentType;
use super::sea_orm_active_enums::ContentVisibility;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "content_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub uploader_id: Uuid,
    pub r#type: ContentType,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub thumbnail_url: Option<String>,
    pub status: ContentStatus,
    pub visibility: ContentVisibility,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub price_cents: i32,
    pub is_paywalled: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::image_sets::Entity")]
    ImageSets,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UploaderId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
    #[sea_orm(has_one = "super::videos::Entity")]
    Videos,
}

impl Related<super::image_sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageSets.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::videos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Videos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
