//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "image_sets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub content_id: Uuid,
    pub layout_preference: Option<String>,
    pub preview_path: Option<String>,
    pub view_count: i64,
    pub unblurred_count: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::content_items::Entity",
        from = "Column::ContentId",
        to = "super::content_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ContentItems,
    #[sea_orm(has_many = "super::images::Entity")]
    Images,
}

impl Related<super::content_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentItems.def()
    }
}

impl Related<super::images::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Images.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
