//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "images")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub image_set_id: Uuid,
    pub storage_path: String,
    pub original_name: String,
    pub sort_order: i32,
    pub alt_text: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::image_sets::Entity",
        from = "Column::ImageSetId",
        to = "super::image_sets::Column::ContentId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ImageSets,
}

impl Related<super::image_sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImageSets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
