//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::TransactionStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub buyer_id: Uuid,
    pub seller_id: Uuid,
    pub content_id: Option<Uuid>,
    pub amount_cents: i32,
    pub status: TransactionStatus,
    #[sea_orm(unique)]
    pub payment_provider_id: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::content_items::Entity",
        from = "Column::ContentId",
        to = "super::content_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ContentItems,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::BuyerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users2,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::SellerId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users1,
}

impl Related<super::content_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContentItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
