//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "video_formats")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "uq_video_formats")]
    pub video_id: Uuid,
    #[sea_orm(unique_key = "uq_video_formats")]
    pub resolution: String,
    #[sea_orm(unique_key = "uq_video_formats")]
    pub format: String,
    pub orig_storage_path: String,
    pub storage_path: Option<String>,
    pub original_name: String,
    pub file_size_bytes: Option<i64>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::videos::Entity",
        from = "Column::VideoId",
        to = "super::videos::Column::ContentId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Videos,
}

impl Related<super::videos::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Videos.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
